[colors.normal]
black = "0x1e1e1e"
blue = "0x0a7aca"
cyan = "0x4ec9b0"
green = "0x4ec9b0"
magenta = "0xc586c0"
red = "0xf44747"
white = "0xd4d4d4"
yellow = "0xffaf00"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xd4d4d4"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.0

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[terminal]

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
opacity = 0.95

[window.padding]
x = 10
y = 10

[keyboard]
