---

- name: restart networkmanager
  systemd:
    name: NetworkManager
    state: restarted

- name: start iptables
  service: name=iptables.service state=started enabled=true

- name: reload iptables
  service: name=iptables.service state=reloaded

- name: start ip6tables
  service: name=ip6tables.service state=started enabled=true

- name: reload ip6tables
  service: name=ip6tables.service state=reloaded
