---

- name: Update pacman cache
  pacman:
    update_cache: yes
  changed_when: false

- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0755'
  loop: "{{ directories }}"

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Enable time synchronization
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started
