---

- name: Install Docker
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Add user to docker group
  user:
    name: "{{ main_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: UFW - Allow Docker bridge
  ufw:
    rule: allow
    interface: docker0
    direction: "{{ item }}"
  loop:
    - in
    - out

- name: Create Docker tools directory
  file:
    path: "{{ homelab_dir }}/docker-tools"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0755'

- name: Copy docker-compose for vulnerable apps
  copy:
    src: docker-compose.yml
    dest: "{{ homelab_dir }}/docker-tools/docker-compose.yml"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0644'
