- name: Setup Blackbox
  hosts: localhost
  become: yes
  vars_files:
    - ../vars/main.yml
  
  roles:
    - { role: base, tags: ['base'] }
    - { role: windowmanager, tags: ['windowmanager'] }
    - { role: virtualization, tags: ['virtualization'] }
    - { role: docker, tags: ['docker'] }
    - { role: security-tools, tags: ['security-tools'] }

  tasks:
    - name: Final system configuration
      debug:
        msg: "Blackbox Setup Complete!"
