- name: Setup Blackbox
  hosts: localhost
  become: yes
  vars_files:
    - ../vars/main.yml
  
  roles:
    - base
    - windowmanager
    #- virtualization
    #- docker
    #- security-tools
    #- vpn-setup
    #- vm-configs
    #- obsidian-vault

  tasks:
    - name: Final system configuration
      debug:
        msg: "Blackbox Setup Complete!"
